### ISSUE TITLE
Shader error in 2018.1

### ISSUE THREAD

**Issue by MaximovInk** [Alx101/Unity2DShadows#1]
In example scene shadows has offset [image](https://ibb.co/dVkbeo) , and some shader have error [image](
https://ibb.co/jXcYQT). Please upgrade to unity 2018.1!

EDIT (@Alx101): For sceneview shadow offset, see #2

**Comment by Alx101** [comment]
@MaximovInk What platform are you running on?

**Comment by Alx101** [comment]
@MaximovInk I have just tested the example scene and the shadows are aligning properly in the render viewport. A thing to note is that since the shadow renderer is using the main camera and not the SceneRenderer camera, the shadows look offset in the SceneView, but in the render viewport you'll see that it renders just fine. 

This is a bug that's been since the beginning, so I'll open up a separate issue (#2) for that and leave the shader error as the topic for this one.

**Comment by itsTheFae** [comment]
I'm having the same issues described here.  It is not working even in builds, the shadows seem to be rendered as if flipped on one axis.    Moving the objects in example scene along X the shadows move "with" the object but moving the objects along Y, their shadows move in opposition to the object position. 

I am running on Windows 7 x64 with Unity 2018.2.8f1.   

I'm still fairly new to shader language and though I've tried to flip the Y axis back I can't seem to find the right spot between the shaders in the package to make that happen.  
If I figure it out I'll post back here, but I could use a pointer on what lines I should be checking and changing if anyone has them.    Thanks! 

**Edited:**   Also, the Unroll error is fairly simple to fix.  If you're not releasing for WebGL, simply remove `UNITY_UNROLL` macro around line 60 of `Distance.shader` and that error will vanish. :)

**Comment by itsTheFae** [comment]
I've found something interesting.   
This issue is result of the `.unitypackage` in this repository being out of date with the repo code itself.   
After finding the culprit of the flip in `Distance.shader` I went to check the repo's version and noticed the missing `#if UNITY_UV_STARTS_AT_TOP` directive.  

I used the `.unitypackage` to import this library, and didn't think to diff it's contents with the current state of the repository. 
I would suggest uploading a new package file to the repo or removing it to avoid this confusion again in the future. 

Thanks for you time!

**Comment by Alx101** [comment]
@itsTheFae Nice catch! I was sure I had updated the .unitypackage, must've completely gone me by. Yes the `UNITY_UV_STARTS_AT_TOP` directive was a fix for when I was testing between windows and mac based unity builds, since it handles UV's differently. I'll make sure to update the .unitypackage.
Thank you for taking the time finding this!
